services:
  app:
    build: .
    ports:
      - "127.0.0.1:4000:4000" # Only expose locally, Caddy will proxy
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/myapp
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password # Change this to a strong password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080" # Only expose locally for security

volumes:
  postgres_data:
